#!/usr/bin/env ruby

Bundler.require
require 'pp'
require 'logger'
$:.unshift("./lib")
require 'avro_consumer'

logger = Logger.new(STDOUT)

group_name = "example-group"

host = ENV.fetch('HOST', 'localhost')
kafka_servers = [
  "#{host}:9092"
]
zookeeper_servers = [
  "#{host}:2181"
]
topic_name = "example_topic"

class ExampleConsumer < AvroConsumer
  self.group_name = "example-group"
  self.topic_name = "example_topic"

  def consume(reader)
    reader.each do |record|
      logger.info "got record: #{record.inspect}"
    end
  end
end


consumer = ExampleConsumer.new(kafka_servers, zookeeper_servers, logger: logger)
consumer.run