#!/usr/bin/env ruby

Bundler.require
require 'pp'
require 'json'
$:.unshift("./lib")
require 'avro_consumer'

logger = Logger.new(STDOUT)

host = ENV.fetch('KAFKA_HOST', 'localhost')
kafka_servers = [
  "#{host}:9092"
]
zk_host = ENV.fetch('ZK_HOST', host)
zookeeper_servers = [
  "#{zk_host}:2181"
]

class PageviewConsumer < AvroConsumer
  self.group_name = "pageviews"
  self.topic_name = "clickstream"

  def consume(reader)
    reader.each do |record|
      next unless record["type"] == "page_view"
      # log "got record: #{record.inspect}"
      data = JSON.parse(record["data_json"])
      log "pageview: #{data["url"]} - #{data}"
    end
  end
end

consumer = PageviewConsumer.new(kafka_servers, zookeeper_servers, logger: logger)
consumer.run
